In [29]:
import numpy as np
import csv
import math
import pandas as pd
from sklearn import preprocessing

In [30]:
user_history = pd.read_csv("user_history.csv")
user_ratings = pd.read_csv("user_ratings.csv")

In [31]:
user_history.head()

USER ID  nectar prague  joshua sleep  gallery fiesta  jerome jazz  \
0   100953       1.484013      0.257857        0.239617     1.133965   
1   100955       1.350588      0.397670        0.308198     0.660640   
2   100965       2.576723      1.098803        1.764609     0.157183   
3   100968       2.307185      0.236830        0.318632     0.594718   
4   100976       0.526058      2.419744        0.548373     0.109904   

   motif polo  zigzag germany  susan sonar  alamo group  gilbert chicken  ...  \
0    0.599283        2.001566     2.007976     1.129472         4.337007  ...   
1    0.900114        1.482669     2.052944     1.052420         3.597033  ...   
2    0.826298        0.094709     4.495690     0.733354         1.453999  ...   
3    0.940251        1.296865     2.451781     1.386342         3.503421  ...   
4    1.261197        5.836276     0.204255     2.655214         0.056144  ...   

   pandora oval  cabinet state  cecilia raja  memo darwin  enigma recycle  \
0      0.489561       0.059119      2.177327     0.063949        1.579579   
1      0.098677       0.201854      1.980738     0.078014        1.692670   
2      2.000441       0.541809      0.045513     2.939113        0.349863   
3      0.037346       0.004922      1.729340     0.302608        1.960916   
4      0.553128       1.847459      1.882823     2.214928        1.869845   

   olivia image  world blonde  begin unit  rodeo santana  drum spring  
0      1.977560      0.009971    0.869408       0.676175     0.977309  
1      2.330878      0.333127    0.942450       0.837264     1.031710  
2      2.440363      2.199525    1.035054       1.466515     0.173144  
3      2.513448      0.776575    0.367702       0.869511     1.108934  
4      2.168439      1.388244    0.081731       0.402835     0.708239  

[5 rows x 101 columns]

In [5]:
user_history.describe()

USER ID  nectar prague  joshua sleep  gallery fiesta  \
count    4500.000000    4500.000000   4500.000000     4500.000000   
mean   113376.351778       1.865722      1.638220        1.143836   
std      7184.873215       0.937386      1.301395        0.743591   
min    100953.000000       0.000558      0.000111        0.000072   
25%    107134.000000       1.096461      0.481934        0.466599   
50%    113286.000000       1.956605      1.250749        1.101720   
75%    119607.250000       2.587191      3.002011        1.780516   
max    125976.000000       4.521661      5.153343        3.125105   

       jerome jazz   motif polo  zigzag germany  susan sonar  alamo group  \
count  4500.000000  4500.000000     4500.000000  4500.000000  4500.000000   
mean      0.985400     1.216889        2.272874     2.374980     1.043467   
std       0.712322     0.794407        2.134627     1.677591     0.717391   
min       0.000407     0.000103        0.000347     0.000068     0.000327   
25%       0.377794     0.562622        0.399109     0.806781     0.461352   
50%       0.850522     1.107225        1.335345     2.102481     0.932965   
75%       1.498610     1.811398        4.952487     4.044239     1.533543   
max       3.748970     4.089940        6.759219     6.565286     3.897725   

       gilbert chicken  ...  pandora oval  cabinet state  cecilia raja  \
count      4500.000000  ...   4500.000000    4500.000000   4500.000000   
mean          1.578136  ...      1.627423       1.036980      1.841324   
std           1.324045  ...      1.128374       0.873155      1.144434   
min           0.000288  ...      0.001380       0.000017      0.000060   
25%           0.504135  ...      0.665749       0.280598      0.785005   
50%           1.002327  ...      1.408540       0.706805      1.890321   
75%           2.959773  ...      2.528821       2.012495      2.770093   
max           5.177968  ...      5.339951       3.002520      5.688518   

       memo darwin  enigma recycle  olivia image  world blonde   begin unit  \
count  4500.000000     4500.000000   4500.000000   4500.000000  4500.000000   
mean      1.875481        1.132869      2.113052      1.509319     0.700393   
std       1.312701        0.697700      0.483498      0.805120     0.410686   
min       0.000289        0.000358      0.411463      0.000562     0.000098   
25%       0.418055        0.563602      1.787143      0.618802     0.328835   
50%       1.934150        1.065851      2.116222      1.839018     0.734343   
75%       3.163269        1.650293      2.443463      2.138760     1.017411   
max       4.505662        3.267691      3.696181      2.965128     1.895920   

       rodeo santana  drum spring  
count    4500.000000  4500.000000  
mean        0.824720     0.686132  
std         0.502802     0.537353  
min         0.000784     0.000001  
25%         0.406434     0.249143  
50%         0.803667     0.548355  
75%         1.198217     1.049258  
max         2.674754     2.818771  

[8 rows x 101 columns]

In [154]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
X = user_history.drop(['USER ID'],axis=1).to_numpy()
pca.fit(X)

print(pca.explained_variance_ratio_)

print(pca.singular_values_)
X_pca = pca.fit_transform(X)
user_history_pca = pd.DataFrame(X_pca, columns = ['pc1', 'pc2', 'pc3'])
user_history_pca['USER ID'] = user_history['USER ID']
user_history_pca

[0.42042748 0.35657495 0.03605765]
[420.13734218 386.91997735 123.03946843]


pc1       pc2       pc3  USER ID
0    -1.176094  8.606512 -1.330745   100953
1    -1.002622  8.207177 -1.497481   100955
2     8.306293 -3.333515 -0.114855   100965
3    -0.764539  8.377915  1.496169   100968
4    -7.572412 -4.342579  0.514051   100976
5    -0.390352  7.758201 -4.076096   100986
6     8.107081 -3.729124  0.015348   100993
7    -6.672780 -4.146363  0.219736   101001
8    -0.356084  8.338444 -2.124662   101010
9    -0.885821  8.567057  1.343266   101013
10    8.383591 -3.315600  0.619571   101016
11   -7.933258 -4.294122  0.738419   101021
12   -7.826932 -4.994858  0.259664   101022
13   -7.167798 -4.642690 -1.082748   101029
14    7.789992 -3.847479 -0.194007   101034
15   -7.659469 -4.544567  0.874968   101039
16   -7.530962 -4.303595  1.260886   101044
17    8.386403 -3.430981 -0.147098   101049
18   -7.727855 -4.142745  1.257408   101053
19   -6.499498 -4.734580 -0.865892   101055
20    7.788446 -3.721070  0.097315   101056
21    8.315918 -3.342300 -0.346176   101062
22    8.609322 -2.792022  0.014344   101072
23   -7.623237 -3.781261 -1.162670   101081
24   -0.550597  8.329935  1.753025   101083
25    8.480821 -4.450827  0.397912   101090
26   -0.277230  7.489854  3.998351   101099
27   -7.585104 -4.613605 -0.074663   101105
28   -0.475208  7.656934 -1.709389   101112
29   -6.593719 -4.398168 -1.278100   101122
...        ...       ...       ...      ...
4470  7.267618 -3.784934  0.318853   125811
4471  8.329575 -3.804976  0.231286   125815
4472  7.494859 -3.803867 -0.005796   125821
4473 -0.368900  7.945306  5.036829   125831
4474  7.142655 -3.978572 -0.377417   125838
4475 -4.940822 -4.806413 -2.286801   125839
4476 -0.776844  7.720087  1.774626   125846
4477 -0.567097  8.085148  2.830918   125852
4478 -0.684876  8.114777 -3.215011   125859
4479 -0.379624  8.361707  3.053699   125866
4480 -0.622299  8.459688 -1.669397   125875
4481 -6.941813 -3.806899 -0.489874   125877
4482 -7.742686 -4.079188  0.735729   125881
4483 -7.416663 -4.340491  2.257717   125889
4484 -0.118073  7.979872  5.305433   125892
4485  8.056864 -3.765894  0.172246   125901
4486 -0.218918  7.770333  5.265288   125908
4487 -0.720741  8.074387  1.303238   125917
4488 -0.606065  8.118241  3.740326   125919
4489 -0.973982  8.418344 -3.159733   125923
4490 -7.182005 -3.843255  1.367565   125930
4491  8.569188 -4.036913  0.119402   125934
4492 -7.868613 -4.403493  1.480004   125944
4493 -1.046664  8.063450 -4.688317   125948
4494 -5.257515 -4.895517 -1.533159   125949
4495  9.081288 -3.866557 -0.203814   125956
4496  7.768702 -3.220798 -0.535944   125959
4497 -0.689955  8.341059 -3.464181   125960
4498  8.066666 -3.949294 -0.442887   125969
4499 -0.830768  8.143994 -1.618999   125976

[4500 rows x 4 columns]

In [7]:
user_ratings.head(5)

USER ID         PRODUCT  RATING
0   100953     spray karma       3
1   100953   nurse october       5
2   100953  balance hostel       3
3   100953    volume pasta       3
4   100953   diana chariot       6

In [8]:
user_ratings.describe()

USER ID         RATING
count  150062.000000  150062.000000
mean   109209.050366       4.998067
std      4740.704035       2.659474
min    100953.000000       0.000000
25%    105088.000000       3.000000
50%    109178.000000       5.000000
75%    113285.000000       7.000000
max    117517.000000      10.000000

In [9]:
user_ratings.isna().sum()

USER ID    0
PRODUCT    0
RATING     0
dtype: int64

In [10]:
type(user_ratings['PRODUCT']), len(user_ratings['PRODUCT'])

(pandas.core.series.Series, 150062)

In [32]:
le_product = preprocessing.LabelEncoder()
le_product.fit(user_ratings['PRODUCT'])
product_ID = le_product.transform(user_ratings['PRODUCT'])

In [33]:
user_ratings['PRODUCT ID'] = product_ID
user_ratings.head()

USER ID         PRODUCT  RATING  PRODUCT ID
0   100953     spray karma       3          80
1   100953   nurse october       5          55
2   100953  balance hostel       3           6
3   100953    volume pasta       3          98
4   100953   diana chariot       6          19

In [21]:
sorted(list(user_history.columns.array))

['USER ID',
 'academy pepper',
 'admiral price',
 'agenda viking',
 'alamo group',
 'algebra small',
 'anvil maestro',
 'axis weekend',
 'bank torch',
 'begin unit',
 'billy parlor',
 'border diet',
 'cabinet state',
 'cake visa',
 'calibre front',
 'carbon carpet',
 'cecilia raja',
 'clever noise',
 'client shake',
 'cliff sherman',
 'climax watch',
 'compact album',
 'context eric',
 'cubic society',
 'dallas level',
 'delphi armani',
 'denver giraffe',
 'deposit hobby',
 'dialog inside',
 'digital wisdom',
 'domino husband',
 'double drink',
 'dragon remark',
 'drum spring',
 'dynamic bonjour',
 'enigma recycle',
 'enjoy reptile',
 'evening cantina',
 'famous genesis',
 'finland jordan',
 'gallery fiesta',
 'gentle visible',
 'gilbert chicken',
 'griffin octopus',
 'halt comet',
 'hamlet orchid',
 'helium eternal',
 'history private',
 'horse spell',
 'hunter edgar',
 'jamaica lecture',
 'jerome jazz',
 'joshua sleep',
 'judo taboo',
 'june galileo',
 'limbo profile',
 'linda villag

In [22]:
sorted(list(pd.unique(user_ratings['PRODUCT'])))

['alaska basil',
 'alcohol future',
 'alice ticket',
 'alien potato',
 'asia jacket',
 'aztec iris',
 'balance hostel',
 'betty today',
 'boston house',
 'bronze sweden',
 'bundle forget',
 'cairo monarch',
 'choice copy',
 'cinema complex',
 'cipher empty',
 'cockpit circle',
 'comedy clean',
 'daniel global',
 'degree forever',
 'diana chariot',
 'diesel jason',
 'diploma vocal',
 'epoxy insect',
 'explain heaven',
 'flame street',
 'fractal heart',
 'fresh shave',
 'frozen command',
 'gelatin prime',
 'glass alpine',
 'good info',
 'gossip cotton',
 'hand inca',
 'harbor moral',
 'helena poncho',
 'henry distant',
 'invent topic',
 'judge sunday',
 'july miami',
 'kermit desert',
 'leonid antenna',
 'lesson switch',
 'lexicon ingrid',
 'liquid baggage',
 'logic channel',
 'loyal jungle',
 'master nobody',
 'medusa cuba',
 'mercy chaos',
 'mineral barcode',
 'moment seminar',
 'motel marvin',
 'neptune before',
 'ninja saga',
 'north speed',
 'nurse october',
 'office triton',
 'pard

In [34]:
le_user = preprocessing.LabelEncoder()
le_user.fit(user_history['USER ID'])
user_ID = le_user.transform(user_ratings['USER ID'])
all_user_ID = le_user.transform(user_history['USER ID'])
user_ratings['NEW USER ID'] = user_ID
user_ratings.head()

USER ID         PRODUCT  RATING  PRODUCT ID  NEW USER ID
0   100953     spray karma       3          80            0
1   100953   nurse october       5          55            0
2   100953  balance hostel       3           6            0
3   100953    volume pasta       3          98            0
4   100953   diana chariot       6          19            0

In [35]:
user_ID, product_ID

(array([   0,    0,    0, ..., 2999, 2999, 2999]),
 array([80, 55,  6, ..., 96,  1, 79]))

In [30]:
rating = user_ratings['RATING'].to_numpy()
rating

array([3, 5, 3, ..., 4, 3, 7])

In [75]:
user_ID_has_rating = np.unique(user_ID)
product_ID_in_train = np.unique(product_ID)
len(user_ID_has_rating), len(product_ID_in_train)

(3000, 100)

In [56]:
user_ratings[user_ratings['NEW USER ID'] == 5].describe().RATING

count    50.000000
mean      5.400000
std       3.016959
min       0.000000
25%       3.000000
50%       5.500000
75%       8.000000
max      10.000000
Name: RATING, dtype: float64

In [57]:
user_rating_stats = []
for user in user_ID_has_rating:
    rating_stats = user_ratings[user_ratings['NEW USER ID'] == user].describe().RATING
    rating_count = rating_stats[0]
    rating_mean = rating_stats[1]
    rating_std = rating_stats[2]
    rating_min = rating_stats[3]
    rating_max = rating_stats[7]
    user_rating_stats.append([user, rating_count, rating_mean, rating_std, rating_min, rating_max])

In [65]:
user_rating_stats_df = pd.DataFrame(user_rating_stats, columns=['NEW USER ID', 'NUM RATING', 'MEAN', 'STD', 'MIN', 'MAX'])
user_rating_stats_df.head()

NEW USER ID  NUM RATING      MEAN       STD  MIN   MAX
0            0        54.0  5.074074  1.931388  1.0   9.0
1            1        47.0  5.297872  1.214315  2.0   8.0
2            2        53.0  4.773585  1.671498  1.0   8.0
3            3        48.0  5.708333  2.843120  1.0  10.0
4            4        37.0  4.567568  3.531922  0.0  10.0

In [66]:
user_rating_stats_df.describe()

NEW USER ID   NUM RATING         MEAN          STD          MIN  \
count  3000.000000  3000.000000  3000.000000  3000.000000  3000.000000   
mean   1499.500000    50.020667     4.998185     2.535261     0.786667   
std     866.169729     4.950125     0.391264     0.797696     0.976801   
min       0.000000    34.000000     3.404255     0.437595     0.000000   
25%     749.750000    47.000000     4.760000     1.977584     0.000000   
50%    1499.500000    50.000000     5.000000     2.632289     0.000000   
75%    2249.250000    53.000000     5.227273     3.145543     1.000000   
max    2999.000000    67.000000     6.604167     4.308554     4.000000   

               MAX  
count  3000.000000  
mean      9.211667  
std       0.971860  
min       6.000000  
25%       9.000000  
50%      10.000000  
75%      10.000000  
max      10.000000

In [69]:
product_rating_stats = []
for product in product_ID_in_train:
    rating_stats = user_ratings[user_ratings['PRODUCT ID'] == product].describe().RATING
    rating_count = rating_stats[0]
    rating_mean = rating_stats[1]
    rating_std = rating_stats[2]
    rating_min = rating_stats[3]
    rating_max = rating_stats[7]
    product_rating_stats.append([product, rating_count, rating_mean, rating_std, rating_min, rating_max])

In [70]:
product_rating_stats_df = pd.DataFrame(product_rating_stats, columns=['PRODUCT ID', 'NUM RATING', 'MEAN', 'STD', 'MIN', 'MAX'])
product_rating_stats_df.head()

PRODUCT ID  NUM RATING      MEAN       STD  MIN   MAX
0           0      1536.0  4.986328  2.629414  0.0  10.0
1           1      1476.0  5.123984  3.016824  0.0  10.0
2           2      1514.0  5.068032  3.367155  0.0  10.0
3           3      1528.0  5.014398  2.055498  0.0   9.0
4           4      1512.0  5.049603  2.672665  0.0  10.0

In [71]:
product_rating_stats_df.describe()

PRODUCT ID  NUM RATING        MEAN         STD         MIN         MAX
count  100.000000   100.00000  100.000000  100.000000  100.000000  100.000000
mean    49.500000  1500.62000    4.998380    2.620342    0.040000    9.970000
std     29.011492    28.46184    0.076259    0.458555    0.196946    0.171447
min      0.000000  1434.00000    4.788152    1.448923    0.000000    9.000000
25%     24.750000  1479.00000    4.956376    2.251127    0.000000   10.000000
50%     49.500000  1502.50000    5.001251    2.655604    0.000000   10.000000
75%     74.250000  1520.00000    5.042819    3.020153    0.000000   10.000000
max     99.000000  1574.00000    5.190860    3.417965    1.000000   10.000000

In [77]:
train_ratio = 0.7
user_ID_to_train = np.random.choice(user_ID_has_rating, int(3000*train_ratio), replace=False)
len(user_ID_to_train)

2100

In [81]:
user_rating_train_df = user_ratings.loc[user_ratings['NEW USER ID'].isin(user_ID_to_train)]
user_rating_val_df = user_ratings.loc[~user_ratings['NEW USER ID'].isin(user_ID_to_train)]
user_rating_val_df

USER ID          PRODUCT  RATING  PRODUCT ID  NEW USER ID
101      100965    helena poncho       4          34            2
102      100965     sushi import       3          83            2
103      100965   balance hostel       6           6            2
104      100965     volume pasta       3          98            2
105      100965    gossip cotton       6          31            2
106      100965    diana chariot       3          19            2
107      100965  mineral barcode       8          49            2
108      100965   cinema complex       4          13            2
109      100965     siren junior       5          78            2
110      100965      north speed       4          54            2
111      100965     sheriff java       6          74            2
112      100965     flame street       7          24            2
113      100965     diesel jason       6          20            2
114      100965      rider shine       5          64            2
115      100965    bundle forget       6          10            2
116      100965     epoxy insect       4          22            2
117      100965    bronze sweden       2           9            2
118      100965   cockpit circle       4          15            2
119      100965    season arthur       4          69            2
120      100965   explain heaven       8          23            2
121      100965       silk gizmo       4          75            2
122      100965    lesson switch       8          41            2
123      100965      saint texas       3          66            2
124      100965     invent topic       8          36            2
125      100965    fractal heart       3          25            2
126      100965     alice ticket       1           2            2
127      100965      choice copy       6          12            2
128      100965    similar malta       3          77            2
129      100965   sabine emotion       5          65            2
130      100965     loyal jungle       4          45            2
...         ...              ...     ...         ...          ...
149985   117512      rider shine       4          64         2998
149986   117512        hand inca       5          32         2998
149987   117512  textile strange       6          86         2998
149988   117512   cockpit circle       6          15         2998
149989   117512     boston house       5           8         2998
149990   117512   frozen command       6          27         2998
149991   117512    lesson switch       4          41         2998
149992   117512    cairo monarch       3          11         2998
149993   117512     invent topic       7          36         2998
149994   117512     alice ticket       3           2         2998
149995   117512  pegasus respond       6          59         2998
149996   117512   sabine emotion       5          65         2998
149997   117512     trivial neon       8          90         2998
149998   117512       tuna relax       3          91         2998
149999   117512    senator ozone       3          71         2998
150000   117512   lexicon ingrid       4          42         2998
150001   117512     motel marvin       6          51         2998
150002   117512      zero nikita       6          99         2998
150003   117512      asia jacket       7           4         2998
150004   117512    parody athena       6          58         2998
150005   117512     judge sunday       6          37         2998
150006   117512    torso cricket       3          88         2998
150007   117512      medusa cuba       5          47         2998
150008   117512        stop door       3          82         2998
150009   117512    theory france       6          87         2998
150010   117512     tunnel nerve       6          92         2998
150011   117512   serial organic       4          72         2998
150012   117512     plume cowboy       6          61         2998
150013   117512     ventura next       5        

In [93]:
train_users = user_rating_train_df['NEW USER ID'].to_numpy()
train_products = user_rating_train_df['PRODUCT ID'].to_numpy()
train_ratings = user_rating_train_df['RATING'].to_numpy()

val_users = user_rating_val_df['NEW USER ID'].to_numpy()
val_products = user_rating_val_df['PRODUCT ID'].to_numpy()
val_ratings = user_rating_val_df['RATING'].to_numpy()

In [90]:
train_user

array([   0,    0,    0, ..., 2999, 2999, 2999])

In [67]:
# from sklearn.model_selection import train_test_split

# train_ratio = 0.7
# train_users = shuffled_users[:int(m*train_ratio)]
# train_products = shuffled_products[:int(m*train_ratio)]
# train_ratings = shuffled_ratings[:int(m*train_ratio)]

# val_users = shuffled_users[int(m*train_ratio):]
# val_products = shuffled_products[int(m*train_ratio):]
# val_ratings = shuffled_ratings[int(m*train_ratio):]
# X = user_ratings.loc[ : , ['PRODUCT ID', 'NEW USER ID']].to_numpy()
# y = user_ratings['RATING'].to_numpy()
# X_train, X_val, train_ratings, val_ratings = train_test_split(X, y, test_size=0.3, random_state=42)

In [122]:
# train_users = X_train[:, 1]
# train_products = X_train[:, 0]
# val_users = X_val[:, 1]
# val_products = X_val[:, 0]
train_users

array([   0,    0,    0, ..., 2999, 2999, 2999])

In [160]:
from sklearn.linear_model import LinearRegression

learning_rate = 0.005
k = 10 # the number of features (for each user/product)
n_users = 3000 # the largest index, plus 1
n_products = 100
m = len(train_user)
# print("n_users, n_products:", n_users, n_products)
np.random.seed(42)

def initialize(n_users, n_products, k):
    """Initalize a random model, and normalize it so that it has sensible mean and variance"""
    # (The normalization helps make sure we start out at a reasonable parameter scale, which speeds up training)
    user_features = np.random.normal(size=(n_users, k))
    product_features = np.random.normal(size=(n_products, k))
    raw_predictions = predict((user_features, product_features))
    
    s = np.sqrt(2*raw_predictions.std()) # We want to start out with roughly unit variance
    b = np.sqrt((5 - raw_predictions.mean()/s)/k) # We want to start out with average rating 5
    user_features /= s
    user_features += b
    product_features /= s
    product_features += b
    raw_predictions = predict((user_features, product_features))
    
    return (user_features, product_features)

def predict(model):
    """The model's predictions for all user/product pairs"""
    user_features, product_features = model
    return user_features @ product_features.T

def single_example_step(model, user, product, rating):
    """Update the model using the gradient at a single training example"""
    user_features, product_features = model
    residual = np.dot(user_features[user], product_features[product]) - rating
    grad_users = 2 * residual * product_features[product] # the gradient for the user_features matrix
    grad_products = 2 * residual * user_features[user] # the gradient for the product_features matrix
    user_features[user] -= learning_rate*grad_users
    product_features[product] -= learning_rate*grad_products
#     print(model[0][0])

def train_sgd(model, epochs):
    """Train the model for a number of epochs via SGD (batch size=1)"""
#     user_features, product_features = model
    # It's good practice to shuffle your data before doing batch gradient descent,
    # so that each mini-batch peforms like a random sample from the dataset
    shuffle = np.random.permutation(m)
    shuffled_users = train_users[shuffle]
    shuffled_products = train_products[shuffle]
    shuffled_ratings = train_ratings[shuffle]
    train_user_raw_ID = le_user.inverse_transform(np.unique(train_users))
    train_history = user_history.loc[user_history["USER ID"].isin(train_user_raw_ID)].drop(['USER ID'],axis=1).to_numpy()
    val_user_raw_ID = le_user.inverse_transform(np.unique(val_users))
    val_history = user_history.loc[user_history["USER ID"].isin(val_user_raw_ID)].drop(['USER ID'],axis=1).to_numpy()
        
    reg = LinearRegression()
    for epoch in range(epochs):
        for user, product, rating in zip(shuffled_users, shuffled_products, shuffled_ratings):
            # update the model using the gradient at a single example
            single_example_step(model, user, product, rating)
        # after each Epoch, we'll evaluate our model
        
        reg.fit(train_history, model[0][np.unique(train_users), :])
#         W = reg.coef_ # regression solution of user_history to user_features
        
        val_user_features = reg.predict(val_history)
        model[0][np.unique(val_users), :] = val_user_features
#         user_features[np.unique(val_users), :] = val_user_features
#         model = (user_features, product)
        predicted = predict(model)
#         print(type(val_user_features),len(val_user_features), len(val_user_features[0]), len(W), len(W[0]), val_history.shape)
#         val_pred = val_user_features @ product_features.T
        train_loss = np.mean((train_ratings - predicted[train_users, train_products])**2)
        val_loss = np.mean((val_ratings - predicted[val_users, val_products])**2)
#         val_loss = np.mean((val_ratings - val_pred[])**2)
        print("Loss after epoch #{} is: train/{} --- val/{}".format(epoch+1, train_loss, val_loss))
    return model[0], model[1], reg

sgd_model = initialize(n_users, n_products, k)
user_features, product_features, reg = train_sgd(sgd_model, 10)

1.375007836186322 5.079726581485755
Loss after epoch #1 is: train/6.461153644127605 --- val/7.1764525187478325
Loss after epoch #2 is: train/2.443495772377914 --- val/6.0591359440247565
Loss after epoch #3 is: train/0.6456128861495742 --- val/5.419721980823555
Loss after epoch #4 is: train/0.40128370183829315 --- val/5.36222857744861
Loss after epoch #5 is: train/0.37832274766615587 --- val/5.361849930497153
Loss after epoch #6 is: train/0.3751229436435438 --- val/5.36250716167887
Loss after epoch #7 is: train/0.37412990924570044 --- val/5.362843338265002
Loss after epoch #8 is: train/0.37337438210249374 --- val/5.3629829367112976
Loss after epoch #9 is: train/0.37255905355515484 --- val/5.363017918131855
Loss after epoch #10 is: train/0.3716054795624212 --- val/5.362988480397324


In [224]:
from sklearn.linear_model import LinearRegression

learning_rate = 0.005
k = 10 # the number of features (for each user/product)
n_users = 3000 # the largest index, plus 1
n_products = 100
m = len(train_user)
# print("n_users, n_products:", n_users, n_products)
np.random.seed(42)

def initialize(n_users, n_products, k):
    """Initalize a random model, and normalize it so that it has sensible mean and variance"""
    # (The normalization helps make sure we start out at a reasonable parameter scale, which speeds up training)
    user_features = np.random.normal(size=(n_users, k))
    product_features = np.random.normal(size=(n_products, k))
    raw_predictions = predict((user_features, product_features))
    
    s = np.sqrt(2*raw_predictions.std()) # We want to start out with roughly unit variance
    b = np.sqrt((5 - raw_predictions.mean()/s)/k) # We want to start out with average rating 5
    user_features /= s
    user_features += b
    product_features /= s
    product_features += b
    raw_predictions = predict((user_features, product_features))
    
    return (user_features, product_features)

def predict(model):
    """The model's predictions for all user/product pairs"""
    user_features, product_features = model
    return user_features @ product_features.T

def single_example_step(model, user, product, rating, alpha):
    """Update the model using the gradient at a single training example"""
    user_features, product_features = model
    residual = np.dot(user_features[user], product_features[product]) - rating
    grad_users = 2 * residual * product_features[product] + alpha * user_features[user] # the gradient for the user_features matrix
    grad_products = 2 * residual * user_features[user] + alpha * product_features[product] # the gradient for the product_features matrix
    user_features[user] -= learning_rate*grad_users
    product_features[product] -= learning_rate*grad_products
#     print(model[0][0])

def train_sgd(model, epochs, alpha):
    """Train the model for a number of epochs via SGD (batch size=1)"""
#     user_features, product_features = model
    # It's good practice to shuffle your data before doing batch gradient descent,
    # so that each mini-batch peforms like a random sample from the dataset
    shuffle = np.random.permutation(m)
    shuffled_users = train_users[shuffle]
    shuffled_products = train_products[shuffle]
    shuffled_ratings = train_ratings[shuffle]
    train_user_raw_ID = le_user.inverse_transform(np.unique(train_users))
    train_history = user_history.loc[user_history["USER ID"].isin(train_user_raw_ID)].drop(['USER ID'],axis=1).to_numpy()
    val_user_raw_ID = le_user.inverse_transform(np.unique(val_users))
    val_history = user_history.loc[user_history["USER ID"].isin(val_user_raw_ID)].drop(['USER ID'],axis=1).to_numpy()
        
    reg = LinearRegression()
    for epoch in range(epochs):
        for user, product, rating in zip(shuffled_users, shuffled_products, shuffled_ratings):
            # update the model using the gradient at a single example
            single_example_step(model, user, product, rating, alpha)
        # after each Epoch, we'll evaluate our model
        
        reg.fit(train_history, model[0][np.unique(train_users), :])
#         W = reg.coef_ # regression solution of user_history to user_features
        
        val_user_features = reg.predict(val_history)
        model[0][np.unique(val_users), :] = val_user_features
#         user_features[np.unique(val_users), :] = val_user_features
#         model = (user_features, product)
        predicted = predict(model)
#         print(type(val_user_features),len(val_user_features), len(val_user_features[0]), len(W), len(W[0]), val_history.shape)
#         val_pred = val_user_features @ product_features.T
        train_loss = np.mean((train_ratings - predicted[train_users, train_products])**2)
        val_loss = np.mean((val_ratings - predicted[val_users, val_products])**2)
#         val_loss = np.mean((val_ratings - val_pred[])**2)
        print("Loss after epoch #{} is: train/{} --- val/{}".format(epoch+1, train_loss, val_loss))
    return model[0], model[1], reg

sgd_model = initialize(n_users, n_products, k)
user_features, product_features, reg = train_sgd(sgd_model, 40, 0.1)

Loss after epoch #1 is: train/6.6527821151771045 --- val/7.218250205625862
Loss after epoch #2 is: train/3.1965401071693 --- val/6.337109812965793
Loss after epoch #3 is: train/0.988218870950714 --- val/5.537715294995877
Loss after epoch #4 is: train/0.5096375647562819 --- val/5.368821100033557
Loss after epoch #5 is: train/0.4334310198822468 --- val/5.3507822380496215
Loss after epoch #6 is: train/0.4135443228712458 --- val/5.347944250415327
Loss after epoch #7 is: train/0.4051750279463596 --- val/5.347540914209322
Loss after epoch #8 is: train/0.40041272191215393 --- val/5.3477236110221655
Loss after epoch #9 is: train/0.39716534191629177 --- val/5.348058497389235
Loss after epoch #10 is: train/0.3946648300581246 --- val/5.3484107774164995
Loss after epoch #11 is: train/0.3925416179027281 --- val/5.348729287058214
Loss after epoch #12 is: train/0.39057078218626845 --- val/5.348989909200755
Loss after epoch #13 is: train/0.3885839448321063 --- val/5.349177256843921
Loss after epoch #1

In [225]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge

learning_rate = 0.005
k = 10 # the number of features (for each user/product)
n_users = 3000 # the largest index, plus 1
n_products = 100
m = len(train_user)
# print("n_users, n_products:", n_users, n_products)
np.random.seed(42)

def initialize(n_users, n_products, k):
    """Initalize a random model, and normalize it so that it has sensible mean and variance"""
    # (The normalization helps make sure we start out at a reasonable parameter scale, which speeds up training)
    user_features = np.random.normal(size=(n_users, k))
    product_features = np.random.normal(size=(n_products, k))
    raw_predictions = predict((user_features, product_features))
    
    s = np.sqrt(2*raw_predictions.std()) # We want to start out with roughly unit variance
    b = np.sqrt((5 - raw_predictions.mean()/s)/k) # We want to start out with average rating 5
    user_features /= s
    user_features += b
    product_features /= s
    product_features += b
    raw_predictions = predict((user_features, product_features))
    
    return (user_features, product_features)

def predict(model):
    """The model's predictions for all user/product pairs"""
    user_features, product_features = model
    return user_features @ product_features.T

def single_example_step(model, user, product, rating, alpha):
    """Update the model using the gradient at a single training example"""
    user_features, product_features = model
    residual = np.dot(user_features[user], product_features[product]) - rating
    grad_users = 2 * residual * product_features[product] + alpha * user_features[user] # the gradient for the user_features matrix
    grad_products = 2 * residual * user_features[user] + alpha * product_features[product] # the gradient for the product_features matrix
    user_features[user] -= learning_rate*grad_users
    product_features[product] -= learning_rate*grad_products
#     print(model[0][0])

def train_sgd(model, epochs, alpha):
    """Train the model for a number of epochs via SGD (batch size=1)"""
#     user_features, product_features = model
    # It's good practice to shuffle your data before doing batch gradient descent,
    # so that each mini-batch peforms like a random sample from the dataset
    shuffle = np.random.permutation(m)
    shuffled_users = train_users[shuffle]
    shuffled_products = train_products[shuffle]
    shuffled_ratings = train_ratings[shuffle]
    train_user_raw_ID = le_user.inverse_transform(np.unique(train_users))
    train_history = user_history.loc[user_history["USER ID"].isin(train_user_raw_ID)].drop(['USER ID'],axis=1).to_numpy()
    val_user_raw_ID = le_user.inverse_transform(np.unique(val_users))
    val_history = user_history.loc[user_history["USER ID"].isin(val_user_raw_ID)].drop(['USER ID'],axis=1).to_numpy()
        
    clf = Ridge(alpha=1.0)
#     reg = LinearRegression()
    for epoch in range(epochs):
        for user, product, rating in zip(shuffled_users, shuffled_products, shuffled_ratings):
            # update the model using the gradient at a single example
            single_example_step(model, user, product, rating, alpha)
        # after each Epoch, we'll evaluate our model
        
#         reg.fit(train_history, model[0][np.unique(train_users), :])
        clf.fit(train_history, model[0][np.unique(train_users), :])
#         W = reg.coef_ # regression solution of user_history to user_features
        
        val_user_features = clf.predict(val_history)
        model[0][np.unique(val_users), :] = val_user_features
#         user_features[np.unique(val_users), :] = val_user_features
#         model = (user_features, product)
        predicted = predict(model)
#         print(type(val_user_features),len(val_user_features), len(val_user_features[0]), len(W), len(W[0]), val_history.shape)
#         val_pred = val_user_features @ product_features.T
        train_loss = np.mean((train_ratings - predicted[train_users, train_products])**2)
        val_loss = np.mean((val_ratings - predicted[val_users, val_products])**2)
#         val_loss = np.mean((val_ratings - val_pred[])**2)
        print("Loss after epoch #{} is: train/{} --- val/{}".format(epoch+1, train_loss, val_loss))
    return model[0], model[1], clf

sgd_model = initialize(n_users, n_products, k)
user_features, product_features, clf = train_sgd(sgd_model, 40, 0.1)

Loss after epoch #1 is: train/6.6527821151771045 --- val/7.2179198467523955
Loss after epoch #2 is: train/3.1965401071693 --- val/6.335265072054294
Loss after epoch #3 is: train/0.988218870950714 --- val/5.534872970267002
Loss after epoch #4 is: train/0.5096375647562819 --- val/5.365743232398776
Loss after epoch #5 is: train/0.4334310198822468 --- val/5.34761238993128
Loss after epoch #6 is: train/0.4135443228712458 --- val/5.344717346606347
Loss after epoch #7 is: train/0.4051750279463596 --- val/5.344273664701075
Loss after epoch #8 is: train/0.40041272191215393 --- val/5.344425994815349
Loss after epoch #9 is: train/0.39716534191629177 --- val/5.3447370868435105
Loss after epoch #10 is: train/0.3946648300581246 --- val/5.345070191489655
Loss after epoch #11 is: train/0.3925416179027281 --- val/5.345372930946951
Loss after epoch #12 is: train/0.39057078218626845 --- val/5.345620386436122
Loss after epoch #13 is: train/0.3885839448321063 --- val/5.345796614603014
Loss after epoch #14 

In [176]:
# user_has_no_rating_ID = le_user.inverse_transform
user_has_no_rating_history = user_history.loc[~user_history['USER ID'].isin(le_user.inverse_transform(user_ID_has_rating))]
user_has_no_rating_history

USER ID  nectar prague  joshua sleep  gallery fiesta  jerome jazz  \
3000   117520       3.000726      0.070635        0.381457     0.257577   
3001   117524       2.583719      1.142150        1.264968     0.063552   
3002   117528       2.027377      0.727344        0.620444     0.712206   
3003   117534       0.501865      3.469311        0.802662     1.371672   
3004   117541       1.799634      0.169895        0.025495     1.046450   
3005   117547       1.246277      0.556756        0.175383     1.520120   
3006   117557       3.536232      1.720407        2.059079     0.549475   
3007   117566       3.299903      0.797886        0.419490     0.512464   
3008   117569       1.667100      0.016625        1.514675     1.828692   
3009   117572       3.341924      1.287243        0.048651     0.453127   
3010   117581       2.252349      0.121661        0.020200     0.823654   
3011   117584       1.413269      0.276754        0.317440     1.291277   
3012   117588       2.735518      1.585549        2.092242     0.407484   
3013   117596       3.119123      1.605016        2.090459     1.014566   
3014   117604       1.882838      0.265293        1.821320     0.282289   
3015   117610       2.152674      1.345704        2.441492     0.301598   
3016   117611       2.256808      0.051779        0.358126     0.700193   
3017   117621       3.361381      1.522499        0.740354     0.895617   
3018   117623       1.576327      0.114161        0.103992     1.332620   
3019   117626       1.224092      3.517673        1.132225     2.291272   
3020   117634       2.812611      0.318333        0.026846     0.738168   
3021   117635       1.202564      3.789795        1.565366     1.843958   
3022   117645       3.718579      0.930974        0.670183     0.843561   
3023   117649       2.433111      0.774829        2.127398     0.075746   
3024   117657       3.139288      1.481050        2.093719     0.151275   
3025   117658       2.181236      0.479281        0.215238     0.011409   
3026   117664       2.937497      0.599788        0.512239     0.321188   
3027   117674       0.219961      2.993508        1.220413     1.527400   
3028   117677       2.366644      0.714438        2.275690     0.126958   
3029   117678       3.482100      1.921154        2.333256     0.886497   
...       ...            ...           ...             ...          ...   
4470   125811       2.931292      1.625673        1.726413     0.688249   
4471   125815       3.014999      1.571864        2.287373     0.440813   
4472   125821       3.301466      1.525631        2.099637     0.612711   
4473   125831       2.880485      0.268904        0.513028     0.292726   
4474   125838       3.241327      2.026840        1.847946     0.842318   
4475   125839       2.410209      4.250939        1.179113     2.978875   
4476   125846       2.408983      0.600111        0.569539     0.346962   
4477   125852       2.471442      0.108514        0.257531     0.663775   
4478   125859       1.581756      0.016784        0.258593     1.000829   
4479   125866       2.994610      0.342407        0.378907     0.312473   
4480   125875       2.106030      0.566418        0.332963     0.855800   
4481   125877       0.366857      2.717611        0.462142     0.537321   
4482   125881       0.668365      3.562219        1.190967     1.114929   
4483   125889       0.071716      3.083242        1.781113     0.970356   
4484   125892       3.578352      0.691451        0.057791     0.340791   
4485   125901       2.292438      1.400577        1.990967     0.514557   
4486   125908       3.161192      1.043711        0.546264     0.146301   
4487   125917       2.431851      0.091861        0.077106     0.687572   
4488   125919       2.396749      0.648838        0.577967     0.116398   
4489   125923       1.935437      0.884689        0.230202     1.269775   
4490   125930       0.171020      2.146185        1.169829     0.704803   
4491   125934       2.774790   

In [177]:
user_has_no_rating_features = reg.predict(user_has_no_rating_history.drop(['USER ID'],axis=1).to_numpy())
len(user_has_no_rating_features), len(user_has_no_rating_features[0])

(1500, 10)

In [178]:
all_user_features = np.concatenate((user_features, user_has_no_rating_features), axis=0)
all_user_predicted = all_user_features @ product_features.T
len(all_user_predicted), len(all_user_predicted[0])

(4500, 100)

In [111]:
val_user_raw_ID = le_user.inverse_transform(np.unique(val_users))
val_history = user_history.loc[user_history["USER ID"].isin(val_user_raw_ID)].drop(['USER ID'],axis=1)
val_history.to_numpy()
len(val_history.to_numpy()), len(val_history.to_numpy()[0])

(900, 100)

In [97]:
train_user_raw_ID = le_user.inverse_transform(np.unique(train_users))
# len(train_user_raw_ID)
train_history = user_history.loc[user_history["USER ID"].isin(train_user_raw_ID)].drop(['USER ID'],axis=1)
np.unique(train_users)

array([   0,    1,    4, ..., 2995, 2996, 2999])

In [75]:
train_user_raw_ID, train_users

(array([100953, 100955, 100965, ..., 117510, 117512, 117517]),
 array([ 576,  227, 1225, ..., 2636, 2936, 2435]))

In [76]:
train_user_raw_ID = np.unique(le_user.inverse_transform(train_users))
train_history = user_history.loc[user_history["USER ID"].isin(train_user_raw_ID)].drop(['USER ID'],axis=1)
train_history

nectar prague  joshua sleep  gallery fiesta  jerome jazz  motif polo  \
0          1.484013      0.257857        0.239617     1.133965    0.599283   
1          1.350588      0.397670        0.308198     0.660640    0.900114   
2          2.576723      1.098803        1.764609     0.157183    0.826298   
3          2.307185      0.236830        0.318632     0.594718    0.940251   
4          0.526058      2.419744        0.548373     0.109904    1.261197   
5          1.022697      0.337878        0.364419     1.780540    0.376503   
6          2.856677      1.122945        1.867636     0.167453    0.654047   
7          1.483582      4.217846        1.229463     2.256226    2.768330   
8          2.208917      0.175096        0.466090     1.790422    0.549158   
9          2.063558      0.275885        0.025109     0.270573    1.610774   
10         2.376851      0.876906        2.380454     0.121075    0.970423   
11         0.380142      2.734971        1.444835     1.443393    2.291426   
12         0.722037      3.409463        1.225953     1.896733    2.044477   
13         1.582887      3.865695        0.627793     2.026267    1.998320   
14         3.488318      1.635379        2.340857     0.608231    0.089074   
15         0.995762      3.685332        1.333167     1.508461    2.201259   
16         0.856779      2.762069        1.449151     1.795617    2.367375   
17         2.564602      0.763548        1.820119     0.904470    1.111684   
18         0.668274      2.997808        1.409591     1.124040    2.114164   
19         1.578671      3.522992        1.091530     1.902251    2.037259   
20         2.662744      1.705678        1.726395     0.391761    0.590564   
21         2.082857      0.838034        1.843062     0.241974    0.852500   
22         1.958980      0.815949        2.020656     0.703160    1.245511   
23         0.137077      2.788735        0.673440     1.434050    1.270661   
24         2.591193      0.123808        0.530539     0.045092    1.044617   
25         2.385603      1.425526        1.770923     0.135175    0.497192   
26         3.001095      0.646320        0.512563     0.029467    1.973922   
27         0.900436      3.240867        1.111371     1.463711    2.138218   
28         2.264592      0.327982        0.448902     0.614715    0.520034   
29         1.456170      3.194457        0.789833     1.429102    0.891660   
...             ...           ...             ...          ...         ...   
2970       1.005897      2.862670        0.275597     1.853627    1.575466   
2971       2.967603      1.303981        2.115853     0.099546    0.701454   
2972       1.902037      3.504689        0.738609     3.176846    2.749225   
2973       2.121042      1.264167        1.888025     0.557380    0.202100   
2974       2.600264      0.388552        0.273472     0.785305    1.520778   
2975       1.842687      0.928516        1.408155     0.551617    0.913952   
2976       2.090624      0.925823        2.672560     0.452008    0.953079   
2977       0.520959      3.209659        1.085091     2.015179    1.560936   
2978       1.503485      3.156167        0.813926     2.204456    2.541148   
2979       2.055411      0.478361        0.459255     0.110264    1.056803   
2980       1.129911      3.188765        0.572767     1.945538    2.078108   
2981       2.691633      0.511245        0.368123     0.405543    1.241901   
2982       1.489651      3.622784        1.447970     1.578400    2.250294   
2983       2.761508      1.273131        1.763797     0.087438    0.167832   
2984       2.195306      4.319396        1.191275     2.875813    3.364424   
2985       1.179443      3.884370        1.583018     2.595934    2.887185   
2986       2.063300      0.756298        1.679944     0.747847    1.427433   
2987       0.411559      2.768771        1.105185     0.789173    1.341678   
2988       2.231780      0.227718        0.834501     0.258761    1.112382   
2989       3.298501      0.1

In [111]:
all_user_features = np.concatenate((user_features, user_has_no_rating_feature), axis=0)
len(all_user_features), len(all_user_features[0])

(4500, 10)

In [123]:
user = 90
product = 10
rating = all_user_features[user] @ product_features[product]
original_user_ID = le_user.inverse_transform([user])[0]
original_product = le_product.inverse_transform([product])[0]
new_rating = pd.DataFrame([[original_user_ID, original_product, rating, product, user]], columns=user_ratings.columns)
new_rating

USER ID        PRODUCT    RATING  PRODUCT ID  NEW USER ID
0   101441  bundle forget  5.929241          10           90

In [191]:
user_product_pairs = list(itertools.product(all_user_ID, np.unique(product_ID)))
submission = pd.DataFrame(user_product_pairs, columns=['NEW USER ID', 'PRODUCT ID'])
submission['USER ID'] = le_user.inverse_transform(submission['NEW USER ID'])
submission['PRODUCT'] = le_product.inverse_transform(submission['PRODUCT ID'])
submission['RATING'] = all_user_predicted.flatten()
submission = submission.drop(['NEW USER ID', 'PRODUCT ID'], axis=1)
submission

USER ID          PRODUCT    RATING
0        100953     alaska basil  2.695802
1        100953   alcohol future  6.674651
2        100953     alice ticket  3.718158
3        100953     alien potato  6.780513
4        100953      asia jacket  3.338592
5        100953       aztec iris  3.550480
6        100953   balance hostel  3.230893
7        100953      betty today  5.307483
8        100953     boston house  7.722644
9        100953    bronze sweden  2.060954
10       100953    bundle forget  6.718227
11       100953    cairo monarch  5.954741
12       100953      choice copy  7.022883
13       100953   cinema complex  6.533891
14       100953     cipher empty  6.185098
15       100953   cockpit circle  6.570910
16       100953     comedy clean  5.912103
17       100953    daniel global  3.531639
18       100953   degree forever  4.015591
19       100953    diana chariot  5.417660
20       100953     diesel jason  5.830994
21       100953    diploma vocal  2.612122
22       100953     epoxy insect  5.949438
23       100953   explain heaven  8.535071
24       100953     flame street  5.781609
25       100953    fractal heart  6.772569
26       100953      fresh shave  6.122637
27       100953   frozen command  2.353103
28       100953    gelatin prime  2.554133
29       100953     glass alpine  4.910842
...         ...              ...       ...
449970   125976    segment meter  4.480988
449971   125976    senator ozone  4.423104
449972   125976   serial organic  5.301735
449973   125976   shannon resume  5.216058
449974   125976     sheriff java  4.811508
449975   125976       silk gizmo  3.831448
449976   125976     silver plate  6.139396
449977   125976    similar malta  4.943683
449978   125976     siren junior  4.534722
449979   125976    solid express  4.593560
449980   125976      spray karma  4.773071
449981   125976     stella micro  5.663030
449982   125976        stop door  4.889405
449983   125976     sushi import  4.530638
449984   125976    tarzan juliet  5.301219
449985   125976    telecom pluto  5.256282
449986   125976  textile strange  5.919726
449987   125976    theory france  5.315268
449988   125976    torso cricket  4.832761
449989   125976    tower fantasy  4.456027
449990   125976     trivial neon  5.033404
449991   125976       tuna relax  4.849036
449992   125976     tunnel nerve  5.129966
449993   125976    turtle pierre  4.640158
449994   125976   update vibrate  6.011233
449995   125976  vampire teacher  5.726130
449996   125976     ventura next  5.571979
449997   125976     vodka bahama  5.457397
449998   125976     volume pasta  6.100381
449999   125976      zero nikita  5.130087

[450000 rows x 3 columns]

In [216]:
user_ratings.head()

USER ID         PRODUCT  RATING  PRODUCT ID  NEW USER ID
0   100953     spray karma       3          80            0
1   100953   nurse october       5          55            0
2   100953  balance hostel       3           6            0
3   100953    volume pasta       3          98            0
4   100953   diana chariot       6          19            0

In [222]:
submission.set_index(['USER ID', 'PRODUCT'])
user_ratings.set_index(['USER ID', 'PRODUCT'])
submission.update(user_ratings)
submission.reset_index(inplace=True)
user_ratings.reset_index(inplace=True)
submission['USER ID'].astype(int)
submission

ValueError: cannot insert level_0, already exists

In [223]:
user_ratings.head()

level_0  index  USER ID         PRODUCT  RATING  PRODUCT ID  NEW USER ID
0        0      0   100953     spray karma       3          80            0
1        1      1   100953   nurse october       5          55            0
2        2      2   100953  balance hostel       3           6            0
3        3      3   100953    volume pasta       3          98            0
4        4      4   100953   diana chariot       6          19            0

In [209]:
rng = [i for i in range(0,10)]
df1 = pd.DataFrame({"USER_ID": rng, 
                    "PRODUCT_ID": rng, 
                    "RATING": rng})


rng_2 = [i for i in range(0,4)]
df2 = pd.DataFrame({'USER_ID' : rng_2,'PRODUCT_ID' : rng_2,
                   'RATING' : [10,10,10,10]})

In [210]:
df1

USER_ID  PRODUCT_ID  RATING
0        0           0       0
1        1           1       1
2        2           2       2
3        3           3       3
4        4           4       4
5        5           5       5
6        6           6       6
7        7           7       7
8        8           8       8
9        9           9       9

In [211]:
df1 = df1.set_index(['USER_ID', 'PRODUCT_ID'])
df2 = df2.set_index(['USER_ID', 'PRODUCT_ID'])
df1

RATING
USER_ID PRODUCT_ID        
0       0                0
1       1                1
2       2                2
3       3                3
4       4                4
5       5                5
6       6                6
7       7                7
8       8                8
9       9                9

In [212]:
df1.update(df2)
df1.reset_index(inplace=True)
df2.reset_index(inplace=True)
df2

USER_ID  PRODUCT_ID  RATING
0        0           0      10
1        1           1      10
2        2           2      10
3        3           3      10

In [214]:
df1

USER_ID  PRODUCT_ID  RATING
0        0           0    10.0
1        1           1    10.0
2        2           2    10.0
3        3           3    10.0
4        4           4     4.0
5        5           5     5.0
6        6           6     6.0
7        7           7     7.0
8        8           8     8.0
9        9           9     9.0

In [195]:
df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],'value': [1, 2, 3, 5]})
df2 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],'value': [5, 6, 7, 8]})
df1

lkey  value
0  foo      1
1  bar      2
2  baz      3
3  foo      5

In [196]:
df2

lkey  value
0  foo      5
1  bar      6
2  baz      7
3  foo      8

In [197]:
df1.merge(df2, left_on='lkey')

TypeError: object of type 'NoneType' has no len()

In [11]:
import itertools
a = [1, ..., 100]
b = [1, ..., 50]
c = [1, ..., 10]
d = [1, ..., 10]
for x in set(itertools.product(a, b)) - set(zip(c, d)):
    print(x)

(Ellipsis, 50)
(100, 50)
(100, Ellipsis)
(1, Ellipsis)
(Ellipsis, 1)
(1, 50)
(100, 1)


In [27]:
res

{(1, 50), (100, 1), (100, 50), (100, Ellipsis), (Ellipsis, 50)}

In [21]:
print(s)

In [18]:
res = []
for x in set(itertools.product(a, b)) - set(zip(c, d)):
    res.append(x)

In [19]:
len(res)

7

In [10]:
set(itertools.product(c, [1,2]))

{(1, 1), (1, 2), (10, 1), (10, 2), (Ellipsis, 1), (Ellipsis, 2)}

In [42]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [44]:
(np.array([[1,2],[3,4]]) @ np.array([[1,2],[3,4]])).flatten()

array([ 7, 10, 15, 22])

In [198]:
pd.DataFrame({'USER ID': range(10), 'PRODUCT ID': range(10), 'RATING': range(10)})

USER ID  PRODUCT ID  RATING
0        0           0       0
1        1           1       1
2        2           2       2
3        3           3       3
4        4           4       4
5        5           5       5
6        6           6       6
7        7           7       7
8        8           8       8
9        9           9       9

In [199]:
pd.DataFrame({'USER ID': range(4), 'PRODUCT ID': range(4), 'RATING': [10]*4})

USER ID  PRODUCT ID  RATING
0        0           0      10
1        1           1      10
2        2           2      10
3        3           3      10

In [200]:
pd.DataFrame({'USER ID': range(10), 'PRODUCT ID': range(10), 'RATING': [10, 10, 10, 10, 4, 5,6,7,8,9]})

USER ID  PRODUCT ID  RATING
0        0           0      10
1        1           1      10
2        2           2      10
3        3           3      10
4        4           4       4
5        5           5       5
6        6           6       6
7        7           7       7
8        8           8       8
9        9           9       9